// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXGM5QXIgrh3h1wiw-i1i5_ja0t90UNg',
    appId: '1:294385749120:web:0ab78705eeec441ec22a65',
    messagingSenderId: '294385749120',
    projectId: 'prueba2crud-c2495',
    authDomain: 'prueba2crud-c2495.firebaseapp.com',
    storageBucket: 'prueba2crud-c2495.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4D2PY8ftGz8i9VND5cEgLc9pQrLgaC6k',
    appId: '1:294385749120:android:c108777a646728d7c22a65',
    messagingSenderId: '294385749120',
    projectId: 'prueba2crud-c2495',
    storageBucket: 'prueba2crud-c2495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW-w2FC1PLcfsFOaFtjGbuimFZJspbPU',
    appId: '1:294385749120:ios:7af3190f6f640aa4c22a65',
    messagingSenderId: '294385749120',
    projectId: 'prueba2crud-c2495',
    storageBucket: 'prueba2crud-c2495.firebasestorage.app',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJW-w2FC1PLcfsFOaFtjGbuimFZJspbPU',
    appId: '1:294385749120:ios:7af3190f6f640aa4c22a65',
    messagingSenderId: '294385749120',
    projectId: 'prueba2crud-c2495',
    storageBucket: 'prueba2crud-c2495.firebasestorage.app',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxXGM5QXIgrh3h1wiw-i1i5_ja0t90UNg',
    appId: '1:294385749120:web:e976d8653c8bba29c22a65',
    messagingSenderId: '294385749120',
    projectId: 'prueba2crud-c2495',
    authDomain: 'prueba2crud-c2495.firebaseapp.com',
    storageBucket: 'prueba2crud-c2495.firebasestorage.app',
  );
}
